backend:
  name: git-gateway

media_folder: id/source/id/shared/images/uploads
public_folder: id/source/id/shared/images/uploads

collections:
  - name: content
    label: Content
    files:
      - name: about
        label: About
        file: id/source/data/content/about.yml
        fields:
          - label: Title
            name: title
            widget: string
          - label: Description
            name: desc
            widget: string
          - label: Item
            name: item
            widget: list
            allow_add: true
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Icon, name: icon, widget: string}
              - {label: Description, name: desc, widget: text}
      - name: team
        label: Team
        file: id/source/data/content/team.yml
        fields:
          - label: Title
            name: title
            widget: string
          - label: Description
            name: desc
            widget: string
          - label: Item
            name: item
            widget: list
            allow_add: true
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Img, name: img, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Description, name: desc, widget: text}
