backend:
  name: git-gateway

media_folder: source/id/shared/images/uploads
public_folder: id/shared/images/uploads

collections:
  - name: content
    label: Content
    files:
      - name: about
        label: About
        file: data/about.yml
        fields:
          - label: Title
            name: title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Item
            name: item
            widget: list
            allow_add: true
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Icon, name: icon, widget: string}
              - {label: Desc, name: desc, widget: text}
  
  - name: settings
    label: Settings
    files:
      - file: data/settings/navigation.yml
        label: Navigation
        name: navigation
        fields:
          - label: Navigation
            name: nav_items
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Path, name: path, widget: string}
      - file: data/settings/units.yml
        label: Units
        name: units
        fields:
          - label: Currency
            name: currency
            widget: select
            options: ['€', '$', '£']
            default: '€'

          - label: Weight
            name: weight
            widget: select
            options: ['kg', ' st', ' lb']
            default: 'kg'

  - name: pages
    label: Pages
    format: yml
    extension: yml
    folder: data/pages/
    create: true
    slug: '{{title}}'
    fields:
      - label: Header
        name: header
        widget: image
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
      - label: Layout
        name: layout
        widget: select
        options: ['normal', ' new_school', ' parent']
        default: ''