backend:
  name: git-gateway

media_folder: source/id/shared/images/uploads
public_folder: id/shared/images/uploads

collections:
  - name: content
    label: Content
    files:
      - name: about
        label: About
        file: data/about.yml
        format: yaml-frontmatter
        fields:
          - label: Title
            name: title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Item
            name: item
            widget: list
            allow_add: true
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Icon, name: icon, widget: string}
              - {label: Desc, name: desc, widget: text}

  - name: products
    label: Products
    files:
      - label: Item
        name: item
        file: data/products.yml
        fields:
          - label: Product
            name: prod_item
            widget: list
            allow_add: true
            fields:
              - {label: Name, name: name, required: true, widget: string}
              - {label: Description, name: description, required: true, widget: text}
